# Business operations for accounts, balances, and transaction history.
# Controllers must verify ownership before calling methods with an account ID.

from decimal import Decimal

from ..accounts import Account
from ..Repositories.accountRepository import AccountRepository
from ..Repositories.transactionRepository import TransactionRepository
from ..transaction import Transaction

class AccountService:
    # Coordinates account persistence and transaction recording.

    def __init__(self, repository: AccountRepository, transactionRepository: TransactionRepository):
        self.repository = repository
        self.transactionRepository = transactionRepository

    async def createAccount(self, userId, accountType: str):
        # Create an account and assign the ID generated by MongoDB.
        account = Account(userId, accountType)
        accountId = await self.repository.create(account.toDict())
        if not accountId:
            raise RuntimeError("Account repository did not return an id")
        account.setAccountId(accountId)
        if not account.getAccountId():
            raise RuntimeError("Account id was not assigned")
        return account
    
    async def getAllAccounts(self, userId: str) -> list[Account]:
        # Return all accounts owned by a user.
        dcs = await self.repository.getAllForUser(userId)
        return [Account.fromDict(d) for d in dcs]

    async def getAccountById(self, accountId: str) -> Account:
        # Return an account or raise ValueError when it does not exist.
        account_dc = await self.repository.getById(accountId)
        if not account_dc:
            raise ValueError("Account not found")
        return Account.fromDict(account_dc)

    async def getAccountDetails(self, accountId: str) -> dict:
        # Combine account metadata with separately stored transactions.
        account = await self.getAccountById(accountId)
        transactions = await self.getTransactionHistory(accountId)
        details = account.getAccountDetails()
        details["Transactions"] = transactions
        return details

    async def deposit(self, accountId: str, amount: Decimal) -> Account:
        # Increase a balance and record the corresponding deposit.
        if amount <= 0:
            raise ValueError("Deposit amount must be greater than zero")

        account = await self.getAccountById(accountId)
        transaction = Transaction("Deposit", amount, accountId)
        await self.repository.updateBalance(accountId, amount)
        await self.transactionRepository.create(transaction.to_dict())
        account.setBalance(amount)
        return account

    async def withdraw(self, accountId: str, amount: Decimal) -> Account:
        # Decrease available funds and record the corresponding withdrawal.
        if amount <= 0:
            raise ValueError("Withdrawal amount must be greater than zero")

        account = await self.getAccountById(accountId)
        if account.getBalance() < amount:
            raise ValueError("Not enough money in account")

        transaction = Transaction("Withdrawal", amount, accountId)
        await self.repository.updateBalance(accountId, -amount)
        await self.transactionRepository.create(transaction.to_dict())
        account.setBalance(-amount)
        return account

    async def getTransactionHistory(self, accountId: str) -> list[Transaction]:
        # Return an account's transactions in chronological order.
        return await self.transactionRepository.getAllForAccount(accountId)
